### ISSUE TITLE
There is a problem on Windows

### ISSUE THREAD

**Issue by Rasool-deldar** [cipherlogs/klassco#1]
I installed your package globally through pnpm and whatever I did, it didn't work and it gives the following error, please fix it.

 klassco -m ./pages
'"C:\Users\user\AppData\Local\pnpm\\global\5\node_modules\klassco\klassco"' is not recognized as an internal or external command,
operable program or batch file.

I installed it through npm, but it didn't run and gave the following error

C:\...\nodejs\node-v20.11.0\\node_modules\klassco\klassco"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by cipherlogs** [comment]
@Rasool-deldar Yes the initial alpha version was only built for linux/mac

but that's okay, remove then install the new version

```bash
npm -g rm klassco
npm -g install klassco
```

when you are using windows use `klassco-win` instead of `klassco`

```bash
klassco-win
```

**Note**: in your example you have used `klassco -m ./pages` and forgot to give a value to `m`.
klassco won't fail it is designed differently even if you give it nonsense `klassco gdjfklajf ./pages` it won't fail on you and it will default to using `-m 2`.

just want you to be aware of that.
[composable-flags](https://klassco.cipherlogs.com/core-concepts/key-features)

**Comment by Rasool-deldar** [comment]
> @Rasool-deldar Yes the initial alpha version was only built for linux/mac
> 
> but that's okay, remove then install the new version
> 
> ```shell
> npm -g rm klassco
> npm -g install klassco
> ```
> 
> when you are using windows use `klassco-win` instead of `klassco`
> 
> ```shell
> klassco-win
> ```
> 
> **Note**: in your example you have used `klassco -m ./pages` and forgot to give a value to `m`. klassco won't fail it is designed differently even if you give it nonsense `klassco gdjfklajf ./pages` it won't fail on you and it will default to using `-m 2`.
> 
> just want you to be aware of that. [composable-flags](https://klassco.cipherlogs.com/core-concepts/key-features)

Thank you very much, it is wonderful 🌹🌹🌹👌
